disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - trailing_newline
  - force_cast
  - variable_name
  - line_length
  - force_try
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - TweetsCounter/Storyboard.swift
  - TweetsCounter/RxSwiftServices/
  - TweetsCounterTests/
# parameterized rules can be customized from this configuration file
line_length: 150
# parameterized rules are first parameterized as a warning level, then error level.
type_body_length:
  - 300 # warning
  - 400 # error

function_body_length:
  - 50
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
