before_install:
  - bundle install
  - brew install swiftlint

# cache:
#   - bundler
#   - cocoapods

osx_image: xcode8.1
language: objective-c
xcode_workspace: TweetsCounter.xcworkspace
xcode_scheme: Tweetometer
script:
    - set -o pipefail && xcodebuild -workspace TweetsCounter.xcworkspace -scheme Tweetometer -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' ONLY_ACTIVE_ARCH=NO | xcpretty
